### ISSUE TITLE
The overflow menu should not show as an icon on devices with a physical menu button

### ISSUE THREAD

**Issue by DvTonder** [jruesga/CMFileManager#14]

**Comment by jruesga** [comment]
INFO: this is not a real ActionBar widget, because i need to use the custom title with splitActionBarWhenNarrow, but this was not working, so i developed a simulated action bar. Also applies to History.

**Comment by DvTonder** [comment]
OK.  Lets leave it as-is then.  It makes for a consistent UI

**Comment by jruesga** [comment]
Working on this.

**Comment by jruesga** [comment]
Done.
