### ISSUE TITLE
File system info box shows wrong warning message

### ISSUE THREAD

**Issue by DvTonder** [jruesga/CMFileManager#17]
The dialog box shows that "file system mounting operations are not allowed in non-privileged mode' when I am running with privileged (advanced) mode on

**Comment by DvTonder** [comment]
Looking at it now, I see the ability to select privileged and non-privileged console in the menu - how is that different from advanced mode?  are they related?

**Comment by jruesga** [comment]
3 navigation modes:
- ChRooted Mode (by default): this allow to access to storage volume only (No root or potential damage actions)
- Advanced Mode - Non Privileged: this creates a non-privileged console, but ask the user when a privileged action is going to happen
- Advanced Mode - Privileged: Full root access

The different is that app ask the user when a privileged action is required

**Comment by DvTonder** [comment]
Hmm, I wonder then if it would not be better to have those as part of the settings itself - just like you set the long-press  action, maybe it would be better from a UX perspective to change the current 'Privileged mode' settings item (was Advanced mode until I changed it yesterday) from a checkbox to a single select list item called 'Access mode' (or something similar) with 3 options - 'Safe mode' (default), 'Prompt user mode' and 'Root access mode'.  That way the item is set in one place.

It would be ideal to then change the strings references to 'console' to something that is more user friendly for non-technical users.

**Comment by jruesga** [comment]
Yes, you are right. More to the list.

**Comment by jruesga** [comment]
Done.
