### ISSUE TITLE
Exit menu

### ISSUE THREAD

**Issue by jruesga** [jruesga/CMFileManager#19]
What do you think about this discussion? http://review.cyanogenmod.com/#/c/25188/

I know that is not a good design, but i don't want have a shell consoles open without any control or any use.

**Comment by DvTonder** [comment]
The 'back' key is exit in ICS and JB, an Exit menu item does not really add any value as long as the back key does the same cleanup as the exit menu item.

**Comment by jruesga** [comment]
But we use the back exist also for navigate (history back)

**Comment by DvTonder** [comment]
Yes, but if you use the back button to go all the way out, it eventually closes the app.

**Comment by jruesga** [comment]
Done.
