### ISSUE TITLE
Change application name to 'File Manager'

### ISSUE THREAD

**Issue by DvTonder** [jruesga/CMFileManager#20]
Discussed the name briefly with Steve and he does not like the use of 'Explorer' in the name - reminds him of windows.  He also feels that the CM branding is not really neccessary - suggestion was to just call it 'File Manager'

**Comment by jruesga** [comment]
Changed name from "CMExplorer" to "File Manager", java package name from "com.cyanogenmod.explorer" to "com.cyanogenmod.filemanager" and android package from "CMExplorer" to "CMFileManager"
