### ISSUE TITLE
Actions menu icon

### ISSUE THREAD

**Issue by DvTonder** [jruesga/CMFileManager#21]
Looking at the new design for the action popup I am a bit concerned that with the new icon on every line it looks really busy.  Also, the actions icon on the bottom left (action bar) and the actions icon in the actions dialog box title is still the 4 arrows icon.

Do we really need the 8 dots icon on every line or can we not just set the long-click to default to actions?

Also, remaining 'arrow' icons need to use the  new icon

**Comment by DvTonder** [comment]
Spoke to Bjorn Lunden (Blunden), he agrees that the icons on every line is a bit much.  The arrows were better but one should also consider removing them altogether and just making the long-press default to actions

**Comment by jruesga** [comment]
Done.
