### ISSUE TITLE
Possible design for tablet

### ISSUE THREAD

**Issue by DvTonder** [jruesga/CMFileManager#25]
Jorge,  I'm wondering about 2 possible design's for the file manager on a tablet:

1) Design 1 - similar to ES File Explorer, when the tablet is in landscape mode just show a 2 column list of the folders/files

2) Design 2 - Use the fragments type layout like Gtalk, gmail etc with the left panel showing the folders and allowing folder navigation and the right panel showing the contents of the folders (files).

I personally think #2 would look better but have not had much experience with fragments to know how difficult it would be do have the two UI's (phone vs tablet).

What do you think?

**Comment by jruesga** [comment]
Yes, i prefer the option 2, also, but i'm afraid that NavigationActivity need to be redesign to fit to FragmentActivity. Also, it requiere new modes for NavigationView (for browsing only folders and browsing only files). I think that more than work with fragments, the difficult will be adapt the actual code to be fragment like. Also, we need to have in mind history, bookmarks and search activities. This option allow to use the left fragmente to show folders, history and bookmarks and right panel to show files and search result.

I see also another possible design: A two panel view with drag & drop between panels like Total Commander.

I still prefer option 2, but in the other hand, i think the option 3 is more easy to implement (doesn't require fragments, and NavigationActivity is prepared to support multiple NavigationViews)

**Comment by DvTonder** [comment]
I had not thought about the total commander type layout - interesting.  I am wondering however how many user will want to drag and drop between folders etc and would need the two pane view?  We should ask around and see what others think.

At this time though the easiest thing to enable would be #1 with a two column listview on rotate.  At least for initial release.  The fragment option (#2) or even #3 would be a longer term feature given the work involved, no?

**Comment by jruesga** [comment]
Yes, changing navigation_view_details.xml and navigation_view_simple.xml to a grid layout, and some tweaks should be enough

**Comment by DvTonder** [comment]
Over to you :-)
