### ISSUE TITLE
crash opening /data/media/ and /sdcard/

### ISSUE THREAD

**Issue by ztNFny** [jruesga/CMFileManager#27]
trying to open either /data/media or /sdcard/ results in a crash. 

Logcat (trying to open /data/media/):

V/ShellConsole(22375): su-readlink, command: cd, args: "/data" && /system/xbin/readlink -f "/data/media" | /system/xbin/awk -F// '{print "\""$1"\""}' | /system/xbin/xargs -n1 /system/xbin/dirname && /system/xbin/readlink -f "/data/media" | /system/xbin/awk -F// '{print "\""$1"\""}' | /system/xbin/xargs -n1 /system/bin/ls -ald
V/ShellConsole(22375): stdin: /
V/ShellConsole(22375): stdin: /data
V/ShellConsole(22375): drwxrwx--- media_rw media_rw          2012-11-02 18:49 media
V/ShellConsole(22375): stdin: /data
V/ShellConsole(22375): drwxrwx--- media_rw media_rw          2012-11-02 18:49 media
V/ShellConsole(22375):
V/ShellConsole(22375): su-readlink, command: cd, exitCode: 0
V/ShellConsole(22375): su-ls, command: cd, args: "/data/media/" && /system/bin/ls -al "/data/media/" | { /system/xbin/grep -v -e '^l' || true; } && echo '>SIMLINKS>' && /system/bin/ls -al "/data/media/" | { /system/xbin/grep -e '^l' || true; } && echo '>SIMLINKS_DATA>' && /system/bin/ls -aF "/data/media/" | /system/xbin/grep -e '^l' | /system/xbin/cut -d ' ' -f2- && /system/bin/ls -aF "/data/media/" | /system/xbin/grep -e '^l' | /system/xbin/cut -d ' ' -f2- | awk '{print "\""$0"\""}' | /system/xbin/xargs -r -n1 /system/xbin/readlink -f && /system/bin/ls -F "/data/media/" | /system/xbin/grep -e '^l' | /system/xbin/cut -d ' ' -f2- | awk '{print "\""$0"\""}' | /system/xbin/xargs -r -n1 /system/xbin/readlink -f | awk '{print "\""$0"\""}' | { /system/xbin/xargs -r /system/bin/ls -ald || echo; }
V/ShellConsole(22375): stdin: /
V/ShellConsole(22375): stdin: drwxrwxrwx u0_a194  u0_a194           2012-06-29 11:32 .AlarmDroid
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-07-29 19:54 .GNotes
V/ShellConsole(22375): drwxrwxrwx u0_a190  u0_a190           2012-07-17 13:11 .com.roflharrison.agenda
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-02 11:02 .config
V/ShellConsole(22375): drwxrwxrwx u0_a130  u0_a130           2012-07-08 02:07 .jota
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-09-27 13:19 Android
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-08 11:04 Audiobooks
V/ShellConsole(22375): -rw-rw-r-- media_rw media_rw    69899 2012-10-29 18:19 Checkliste_Gebrauchtwagenverkauf.pdf
V/ShellConsole(22375): -rw-rw-rw- root     root      1369717 2012-06-21 00:50 Chronicles.Sale.v2.0.pdf
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-11 19:24 Cut the Rope
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-11-01 21:39 Cyandelta
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-09 21:49 DCIM
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-11-02 18:27 Download
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-18 10:10 LuckyPatcher
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-09-22 20:35 MinimalisticTextPreferences
V/ShellConsole(22375): drwxrwxrwx root     root              2012-09-28 14:05 Music
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-01 15:21 Notifications
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-07-05 17:18 Pictures
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-09-04 17:03 Recordings
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-11 13:31 Ringtones
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-26 11:16 Scoreloop
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-27 19:21 SpeedSoftware
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-31 15:15 Tasker
V/ShellConsole(22375): drwxrwxrwx root     root              2012-11-01 02:09 TitaniumBackup
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-06-23 04:00 WhatsApp
V/ShellConsole(22375): drwxrwxrwx u0_a51   u0_a51            2012-08-16 18:10 android
V/ShellConsole(22375): -rw-rw-rw- root     root      8899731 2012-10-30 21:29 android42_keyboard_signed.zip
V/ShellConsole(22375): -rw-rw-r-- media_rw media_rw   854122 2012-11-02 18:47 battery_history.txt
V/ShellConsole(22375): -rw-rw-rw- media_rw media_rw  6502457 2012-11-02 18:24 betterlatitude.log
V/ShellConsole(22375): -rw-rw-rw- media_rw media_rw    44783 2012-08-26 00:54 bmw_crash_reports.txt
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-11-02 14:49 clockworkmod
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-19 11:38 com.alk.copilot.eumarket.premiumeupan
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-08-16 17:42 data
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-08-19 23:59 ebanking
V/ShellConsole(22375): -rw-rw-rw- media_rw media_rw 20971520 2012-06-23 00:10 efs_backup_23Jun12.img
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-11-02 14:47 extracted
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-11 19:36 ggtmp
V/ShellConsole(22375): -rw-rw-r-- media_rw media_rw      257 2012-10-28 13:23 mail
V/ShellConsole(22375): -rw-rw-r-- media_rw media_rw      223 2012-10-27 15:32 mail.gz
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-10-03 17:06 media
V/ShellConsole(22375): -rw-rw-r-- media_rw media_rw       24 2012-10-06 23:01 miniclipId.txt
V/ShellConsole(22375): -rw-rw-rw- media_rw media_rw      121 2012-06-23 18:40 mm_uuid.info
V/ShellConsole(22375): -rw-rw-rw- media_rw media_rw      302 2012-08-07 11:29 mount_info.txt
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-26 13:54 openfeint
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-11-01 23:32 pmw
V/ShellConsole(22375): -rw-rw-rw- media_rw media_rw     2989 2012-08-07 11:29 process_info.txt
V/ShellConsole(22375): -rw-rw-rw- u0_a98   u0_a98      46966 2012-07-02 13:41 secrets
V/ShellConsole(22375): drwxrwxr-x media_rw media_rw          2012-10-28 13:13 sl4a
V/ShellConsole(22375): -rw-rw-r-- media_rw media_rw    28735 2012-11-02 18:26 sms_backup_plus.log
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-06-22 13:18 svox
V/ShellConsole(22375): drwxrwxrwx media_rw media_rw          2012-11-01 21:34 updates
V/ShellConsole(22375): >SIMLINKS>
V/ShellConsole(22375): >SIMLINKS_DATA>
V/ShellConsole(22375): stdin: /
V/ShellConsole(22375): stdin:
V/ShellConsole(22375): su-ls, command: cd, exitCode: 0
D/dalvikvm(22375): GC_CONCURRENT freed 5436K, 61% free 4797K/12288K, paused 5ms+3ms, total 53ms
W/ResourceType(22375): No package identifier when getting value for resource number 0x00000000
D/AndroidRuntime(22375): Shutting down VM
W/dalvikvm(22375): threadid=1: thread exiting with uncaught exception (group=0x41f27300)
E/AndroidRuntime(22375): FATAL EXCEPTION: main
E/AndroidRuntime(22375): android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime(22375):        at android.content.res.Resources.getValue(Resources.java:1013)
E/AndroidRuntime(22375):        at android.content.res.Resources.getDrawable(Resources.java:658)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.ui.IconHolder.getDrawable(IconHolder.java:55)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.adapters.FileSystemObjectAdapter.processData(FileSystemObjectAdapter.java:226)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.adapters.FileSystemObjectAdapter.notifyDataSetChanged(FileSystemObjectAdapter.java:164)
E/AndroidRuntime(22375):        at android.widget.ArrayAdapter.addAll(ArrayAdapter.java:198)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.ui.widgets.NavigationView.loadData(NavigationView.java:942)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.ui.widgets.NavigationView.onPostExecuteTask(NavigationView.java:887)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.ui.widgets.NavigationView$2.onPostExecute(NavigationView.java:843)
E/AndroidRuntime(22375):        at com.cyanogenmod.filemanager.ui.widgets.NavigationView$2.onPostExecute(NavigationView.java:746)
E/AndroidRuntime(22375):        at android.os.AsyncTask.finish(AsyncTask.java:631)
E/AndroidRuntime(22375):        at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(22375):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
E/AndroidRuntime(22375):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22375):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(22375):        at android.app.ActivityThread.main(ActivityThread.java:4931)
E/AndroidRuntime(22375):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(22375):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(22375):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime(22375):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
E/AndroidRuntime(22375):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  334):   Force finishing activity com.cyanogenmod.filemanager/.activities.NavigationActivity

**Comment by jruesga** [comment]
I'll try to reproduce the error.

**Comment by jruesga** [comment]
I reviewed the exception, and the result of your ls command. I tested it parsing the result from your logcat and i haven't found any problem.
From the exception the problem is in the resolution of the file to an appropriate mime/type drawable, so something must be wrong on drawables, but i couldn't find it.

Anyway, i put a patch on gerrit for avoid using invalid references of drawables, using default drawable in this case. Also the invalid mimetype and file is putting in the logcat as a warning. Please, checkout the change http://review.cyanogenmod.com/#/c/25839/ from cyanogenmod gerrit and report back.

Thanks

**Comment by ztNFny** [comment]
I'm currently without a build environment as I'm on a job. I'll have to wait till it's in a CM build, will report back then.

**Comment by ztNFny** [comment]
Did some more experiments with the different mime types in that folder and figured out what's causing it: a .ods file.
I noticed that one is not listed in the logcat output even though it exists in the folder. No idea at all why that is _confused_.

To repoduce just "touch test.ods" and try to open that folder.

**Comment by jruesga** [comment]
A typo in mime file list. Fixed here: http://review.cyanogenmod.com/#/c/25838/
