### ISSUE TITLE
Inability to move files.

### ISSUE THREAD

**Issue by rmblau** [jruesga/CMFileManager#31]
It is impossible as of this posting to move files between directories or otherwise organize files on the phone.

**Comment by jruesga** [comment]
I am aware of this. It's a problem with the mv command. It fail to stat when moving from sdcard to system filesystem. Let me try tonight if i can find a fix for this, or at least use copy-delete when source file is in a sdcard filesystem.

**Comment by jruesga** [comment]
Fixed here: http://review.cyanogenmod.org/#/c/25969/
