### ISSUE TITLE
Error when moving file to root of "sdcard"

### ISSUE THREAD

**Issue by TimeLincoln** [jruesga/CMFileManager#32]
When trying to move a file to the /data/media or the root of the "sdcard" on my maguro, I get the error "operation is not permitted in the current folder" even when in root mode.

**Comment by jruesga** [comment]
Are you trying to move a file in the same directory? For move and paste operations the default behaviour is select the files or folders, navigate to destination folder and the make the move or paste operation. For operations in the same folder you can loong-click the item and select create copy or rename operations.

**Comment by TimeLincoln** [comment]
It could be trying to do that.  So here's what happens.  I select a file in the root of the "sdcard" and move it to another directory, without deselecting it, i try to move it back to the root of the "sdcard".  I guess its still forming the command based on the previous location?

Edit: got the flow a bit wrong.  When you move it, it gets deselected, but i just select the same file and try to move it back, and get the error.

Edit 2: also found another strange behavior, I can select a file in a folder, back out of that folder, then go back in and select the file again, it will show me having two files selected, it doesn't work again after that, just shows two files selected.

**Comment by jruesga** [comment]
I cannot reproduce any of this behaviours. I tried both on sdcard and it works for me.

Is still present this bug after change http://review.cyanogenmod.org/#/c/25969/? If it still presents, could you enable debugging in settings and attach a logcat of both bugs?

**Comment by TimeLincoln** [comment]
I'll do another build tonight and test again. Will attach logcats of the
issue, possibly upload video to youtube if necessary.

On Tue, Nov 6, 2012 at 5:03 PM, Jorge Ruesga notifications@github.comwrote:

> I cannot reproduce any of this behaviours. I tried both on sdcard and it
> works for me.
> 
> Is still present this bug after change
> http://review.cyanogenmod.org/#/c/25969/? If it still presents, could you
> enable debugging in settings and attach a logcat of both bugs?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jruesga/CMFileManager/issues/32#issuecomment-10129713.

## 

Amar Rajvanshi

E: amarkrajvanshi@gmail.com
P: (240) 366-7906

**Comment by jruesga** [comment]
@TimeLincoln, did you reproduce the bug?

**Comment by TimeLincoln** [comment]
I have reproduced the error, but not the selection duping.

On Sun, Nov 11, 2012 at 12:40 PM, Jorge Ruesga notifications@github.comwrote:

> @TimeLincoln https://github.com/TimeLincoln, did you reproduce the bug?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jruesga/CMFileManager/issues/32#issuecomment-10269742.

## 

Amar Rajvanshi

E: amarkrajvanshi@gmail.com
P: (240) 366-7906

**Comment by jruesga** [comment]
logcat?

**Comment by jruesga** [comment]
No logcat. Closed
