### ISSUE TITLE
com.cyanogenmod.filemanager.console.CommandNotFoundException: bash

### ISSUE THREAD

**Issue by killerkink** [jruesga/CMFileManager#34]
I keep getting this error when trying to use CM FileManager on my CM10 rom. In the command list xml, bash refer to /system/bin/sh. This is definitely available.

Any clue on where to look to resolve this?

**Comment by jruesga** [comment]
What device are you running?
Official or based CM10 rom?
Could you enable log debugging in general settings and attach a logcat?

Thanks.

**Comment by killerkink** [comment]
Thanks for taking the time to reply. I have just managed to resolve the issue. It seem that CMFileManager require some softlink to toolbox instead of busybox and I corrected it. Although the error refer to bash and unable to create console, the real issue was not due to that. I am using unofffical CM10 port for p76ti allwinner tablet and I do appreciate that you take the time to respond.
