### ISSUE TITLE
Send *.apk files via bluetooth

### ISSUE THREAD

**Issue by AChep** [jruesga/CMFileManager#37]

**Comment by jruesga** [comment]
Bluetooth app only supports tje next mime/types:

image/*
video/*
audio/*
text/x-vcard
text/plain
text/html
application/zip
application/vnd.ms-excel
application/msword
application/vnd.ms-powerpoint
application/pdf

**Comment by AChep** [comment]
Sad, but some file managers (for example Root Explorer) can do it.

**Comment by jruesga** [comment]
Yes, but they are forcing to the bluetooth app to something that it has not defined. CMFM only ask for apps that have declared support to handle the file. Sorry, but i'm not going to change that

**Comment by jruesga** [comment]
http://review.cyanogenmod.org/#/c/36409/
