### ISSUE TITLE
I miss this app.

### ISSUE THREAD

**Issue by a-raccoon** [jruesga/CMFileManager#42]
I understand CM is gone, and LOS uses the AOSP file manager (which is essentially the what CMFileManager evolved from).  Is CMFM still being maintained anywhere, I hope?  The latest releases I found were from 2014 at this fork -> https://github.com/CyanogenMod/android_packages_apps_CMFileManager

**Comment by jruesga** [comment]
Sorry, but I'm not maintaining the app anymore. There are a lot of filemanagers in the playstore (and with material design).

**Comment by a-raccoon** [comment]
Indeed.

I wonder if maybe it's material design that makes them all terrible.
